### ISSUE TITLE
In-game config doesn't render inventory size changes

### ISSUE THREAD

**Issue by IronPiston** [copygirl/WearableBackpacks#105]
In [this video](https://twitter.com/koppeh/status/832019096803885057), the in-game config actively renders the inventory size. This feature doesn't seem to be working on 3.1.3 
on Forge 14.23.5.2808

https://imgur.com/a/SHzFrNm

**Comment by copygirl** [comment]
If you're talking about the way the config setting is rendered as a simple box rather than the cool "preview" in the video, that's because the config GUI has been completely remade from scratch and I was able to make an actual generic control for a "2D slider". I thought this was sufficient, re-creating the look was actually not trivial.

In case you meant the setting itself not affecting backpacks immediately, that's due to the decision that it doesn't affect placed / worn backpacks, so there's no question about what happens to items that overflow. In the video you see me breaking the backpack between each change. As an item it doesn't retain its size. (Unless you give it a custom size in the NBT data, that is.)

**Comment by copygirl** [comment]
Considering this answered.
