### ISSUE TITLE
Configuration Issue.

### ISSUE THREAD

**Issue by BadGirlMarc** [copygirl/WearableBackpacks#140]
I guess the only way to really say this is that the config options are not working in the slightest, and I mean everything. Could it be due to the fact I'm on a server? Really hope there's a fix for this because I do indeed enjoy this mod.

**Comment by copygirl** [comment]
On a server, you need to modify its config file directly. Changing settings on the client doesn't do anything since they will be synchronized from server to client upon connecting - with the exception of client-side settings like the opacity of the enchantment effect on worn backpacks.

You could use the GUI to change any settings to what you'd like, then copy the `config/WearableBackpacks.cfg` file from your client to the server directory. You will need to restart the server once for it to read the new settings.

I hope this helps / works.

**Comment by BadGirlMarc** [comment]
I don't know how to do any of this, sorry for being a pain.

**Comment by copygirl** [comment]
You could try to look up a walk-through on how to edit / copy server side options or config files. Good luck. Will close for now.
