### ISSUE TITLE
Adding non-backpack stuff?

### ISSUE THREAD

**Issue by Auton-Baz** [copygirl/WearableBackpacks#18]
Are you going to add lockers, crates and chests like those on BettterStorrage?

**Comment by copygirl** [comment]
No, unfortunately not. I'm focusing on re-releasing backpacks because they were my favorite feature. It's unlikely I'll get to much else. Next on the list would be crates but they're almost as big of an undertaking as backpacks, and would also require a complete rewrite as well as a redesign in my opinion.
