### ISSUE TITLE
Backpack does not equip when broken

### ISSUE THREAD

**Issue by Thyriel** [copygirl/WearableBackpacks#53]
Somehow it just isn't working with the default config file. Neither can i equip the backpack in chest slot nor does it display any defense values on it. I tried cheated and crafted backpack as well.

**Comment by copygirl** [comment]
What happens if you sneak and break it? Does it show a message in the chat? Does it refuse to break? Does it not get equipped when broken?

Are you using a mod to display defense values? I think the reason why they're missing is due to the backpack not being actual armor, but using Forge's `ISpecialArmor` to act just like one. What's that mod called again? Maybe it's possible to add support for it!

**Comment by Thyriel** [comment]
sneak/break: collected like a normal item in free inventory slot. No chat message displayed

**Comment by Thyriel** [comment]
Just tried without any other mods and still the same. I guess either a general problem in 1.12.2 or with newer forge versions (using 14.23.0.2501)

**Comment by copygirl** [comment]
Haven't had the chance to reproduce this yet but I will certainly look into it and fix it for the next version, I think. That might take some time still.

**Comment by Thyriel** [comment]
Don't ask me why but somehow it's working now (maybe because i updated Forge to 2512 ?)

**Comment by copygirl** [comment]
I was actually wondering if it was due to a change in Forge code. Looks like it was even a bug! Yay for me not having to look into it!
