### ISSUE TITLE
Inventory Tweaks sorting doesn't work in backpacks

### ISSUE THREAD

**Issue by Boymann** [copygirl/WearableBackpacks#67]
MC: 1.12.2
Forge: 2568
InventoryTweaks: 1.64-dev
Wearablebackpacks: 1.12.2-3.1.0

**Comment by copygirl** [comment]
Inventory Tweaks support has been removed because the @RX14's maven repository I used for it went down or so while I was trying to push a much needed update, and InvTweaks wasn't updated at the time. Though it was quite a pain, as he needed to patch the build file to make it work, even.

My focus is currently on other things, and I really don't feel like messing with Java, Gradle, and dependencies right now. Maybe someone else feels like tackling this? As long as the API hasn't changed much: The code for InvTweaks is still there, just commented out.

**Comment by copygirl** [comment]
Inventory Tweaks support has been removed because the @RX14's maven repository I used for it went down or so while I was trying to push a much needed update, and InvTweaks wasn't updated at the time. Though it was quite a pain, as he needed to patch the build file to make it work, even.

My focus is currently on other things, and I really don't feel like messing with Java, Gradle, and dependencies right now. Maybe someone else feels like tackling this? As long as the API hasn't changed much: The code for InvTweaks is still there, just commented out.

**Comment by RX14** [comment]
Yeah, my repository will be down forever, unfortunately :(

Not sure what you can do to replace it.

**Comment by copygirl** [comment]
Fixed in 31cd7562742eb54fcd27407463b2544d3bec0ba7.

**Comment by RX14** [comment]
Sorry for breaking your stuff :(

**Comment by copygirl** [comment]
@RX14 As long as you only break Inventory Tweaks...

Just kidding! It's absolutely fine! Thanks for putting in the time back then to make it work! ❤️
