### ISSUE TITLE
Can Remove From Slot In Non-Vanilla Inventory GUIs

### ISSUE THREAD

**Issue by InsomniaKitten** [copygirl/WearableBackpacks#71]
When accessing the chestplate slot via a third party GUI such as the Baubles or Aether Legacy inventories, the equipped wearable backpack can be freely removed from its slot.

**Mod version:** [3.1.2](https://minecraft.curseforge.com/projects/wearable-backpacks/files/2525511)
**Forge version:** [1.12.2-14.23.2.2612](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.2.2612/forge-1.12.2-14.23.2.2612-changelog.txt)

**Baubles version:** [1.5.2](https://minecraft.curseforge.com/projects/baubles/files/2518667)
**Aether Legacy version:** [2.0](https://minecraft.curseforge.com/projects/aether-legacy/files/2520541)

**Comment by copygirl** [comment]
This is the reason why we need a `canUnequip` method on items or similar. Way back, I wanted to create a Forge PR to introduce this, in a way that would work for any number of custom equipment slots, but it was left to rot.

The only reason the backpack can't be removed from the Vanilly inventory GUI slot is because I [replace](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/java/net/mcft/copy/backpacks/ProxyCommon.java#L242) the armor slot with [my own](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/java/net/mcft/copy/backpacks/container/SlotArmorBackpack.java).

This is already highly questionable but really the only way I could think of making backpacks work without interacting with the (in my opinion, back then, toxic) Forge community and waiting multiple months.

Obviously the current solution could be expanded to also replace other mod container slots through hacky ways, but I personally couldn't be bothered back then nor now. Sorry.

**Comment by asiekierka** [comment]
But I can be bothered! Expect a fix for this in a few days.

**Comment by asiekierka** [comment]
I'll be busy for most of today - if you pull it off before me, I won't do it obviously :P
