### ISSUE TITLE
Compatibility with Baubles

### ISSUE THREAD

**Issue by vpontin** [copygirl/WearableBackpacks#95]
Will us see this soon?

I mean, with baubles installed we could equip the backpack on a bauble slot (instead of the armor).

Thanks in advance!!

**Comment by vpontin** [comment]
So if i check this option off i will be able to equip the backpack on one of the bauble slots?

**Comment by copygirl** [comment]
It won't take up any slot, then.

Bauble compatibility is a fickle thing because Baubles, just like Vanilla, doesn't allow items to control whether they can be equipped / unequipped. So I have to hack in a custom slot that will prevent taking the backpack off. Another problem is that there's no "back" Bauble slot or any fitting slot the backpack should take up.

**Comment by copygirl** [comment]
Ah, I suppose. And it's also called "body" slot officially it seems, so it could be a worthwhile alternative. Again, #52 would be the issue that's tracking this feature. Not sure if @InsomniaKitten is interested in implementing this. She's maintaining WBs, now!
